org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=512m
org.gradle.java.home=/Users/imukulgehlot/Library/Java/JavaVirtualMachines/ms-17.0.15/Contents/Home
android.useAndroidX=true
android.enableJetifier=false
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
